### ISSUE TITLE
Control crushes on some web sites

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuza55/csexwb2#20]
```
What steps will reproduce the problem?
1. if you will visit the following site : http://www.alarabiya.net
2. the control will crush , and there is no whay to stop or even handle 
that in .NET!!!
3. Please note that i had the same problem when using IE6 , it also 
crushes, it is seems that there is some problem with JS excuting there, 
but IE7 (and i using it now) & any version of Opera

What is the expected output? What do you see instead?
It should of course not crush, it seems to be COM issue becuse *some 
times* it will produce "Memory protection vilotion" in .NET

What are the OS and IE versions?
Win Vista Home Ultimate, IE7

What version of the product are you using?
1.0.0.7

Please provide any additional information below.
I afraid that this can hapen with a lot of other sites as was hapenning 
with IE6
```

Original issue reported on code.google.com by `TMS2...@gmail.com` on 14 Jan 2008 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
I can not reproduce the crash by visiting http://www.alarabiya.net. Using 
Vista, IE7.

What is the exact error message after a crash?

MH


```

Original comment by `mehr...@gmail.com` on 14 Jan 2008 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Starnge I just tried it again and it crushed.
As i said there is no error meesage except the dump info returned by WinVista 
as 
follows :

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: DemoApp.exe
  Application Version:  1.0.0.0
  Application Timestamp:    4784bc19
  Fault Module Name:    PNCRT.dll <<<----- I don't know if this will help you
  Fault Module Version: 6.0.0.0
  Fault Module Timestamp:   3b332173
  Exception Code:   c0000005
  Exception Offset: 0000fab9
  OS Version:   6.0.6000.2.0.0.768.3
  Locale ID:    1033
  Additional Information 1: 8d13
  Additional Information 2: cdca9b1d21d12b77d84f02df48e34311
  Additional Information 3: 8d13
  Additional Information 4: cdca9b1d21d12b77d84f02df48e34311

Read our privacy statement:
  http://go.microsoft.com/fwlink/?linkid=50163&clcid=0x0409

```

Original comment by `TMS2...@gmail.com` on 18 Jan 2008 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Yes and *some times* .net framework gives the folowing error :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AccessViolationException: Attempted to read or write protected memory. 
This 
is often an indication that other memory is corrupt.
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr 
hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr 
wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
DemoApp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Windows%20Vertual%
20Folders/Desktop/csExWB_1_0_0_7/csExWB/DemoApp/bin/Release/DemoApp.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/S
ystem.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.
Drawing.dll
----------------------------------------
csExWB
    Assembly Version: 1.0.0.7
    Win32 Version: 1.0.0.7
    CodeBase: file:///F:/Windows%20Vertual%
20Folders/Desktop/csExWB_1_0_0_7/csExWB/DemoApp/bin/Release/csExWB.DLL
----------------------------------------
Interop.CSEXWBDLMANLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Windows%20Vertual%
20Folders/Desktop/csExWB_1_0_0_7/csExWB/DemoApp/bin/Release/Interop.CSEXWBDLMANL
ib.DL
L
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essib
ility.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: 
file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Mi
croso
ft.mshtml.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
    CodeBase: 
file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.W
eb.dl
l
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original comment by `TMS2...@gmail.com` on 18 Jan 2008 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
First crash: PNCRT.dll
The library file pncrt.dll, contains program code used by RealOne Player. Some 
users 
may experience troubles if this dll file is missing or corrupted. The best 
solution 
in such cases would be that you uninstall and reinstall the program that uses 
the 
pncrt.dll file, like for example the RealPlayer program.

As for the Second crash, would you post the URL.

MH
```

Original comment by `mehr...@gmail.com` on 18 Jan 2008 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
Dear Merhant

Acctually i have no realplayer on my machine but i have k-lite codec pack that 
installs some realpalyer codecs, i will try to install realplayer or reinstall 
codec 
pack and will inform you accordingly, but honestly i don't think that it is the 
problem becuase IE7 on the same machine opens the web site very well without 
problems, in second hand if you will check HTML source for this website you 
will 
find a reference for windows media ActiveX not real's one, and another thing i 
just 
noted i think it the reason of the crush, when opening the site in IE7 a tiny 
bar on 
the top of the page will be showed by IE7 that this page requesting to run 
windows 
media extention AcitveX, would you like to....
As for the above mentioned crash, the report i posted is actually for the same 
crash! first one is the error reported by winVista error reporting tool and the 
second that apears after closing the first one is .Net standart unhandled error 
dialog.
```

Original comment by `TMS2...@gmail.com` on 19 Jan 2008 at 12:16

**Comment by GoogleCodeExporter** [comment]
```
If you still experience crashes, I suggest create a fresh project with one form 
and 
place an instance of cExWB control on it and then navigate to the problem 
sites. The 
reason is that DemoApp is exactly that, A demo, which contains bugs for sure. A 
small and simple project should be easier to debug and to trace any problems if 
it 
relates to the control.

As for PNCRT.dll, this control does not use or reference such dll. Most likely, 
it 
is being loaded by webbrowser control to perform some action in respond to a 
piece 
of code contained within the page. I did check the source of the page and it 
conatins a reference to Flash (the add on the right side) not media player.

MH
```

Original comment by `mehr...@gmail.com` on 19 Jan 2008 at 4:21

**Comment by GoogleCodeExporter** [comment]
```
Waw, i should admit that you was right!
I just installed latest version of RealPlayer 11 Beta, and the site now opens 
without any crushes, but even so i could not understand why this hapens, and 
should 
we do something to prevent the crush as IE7 was opening it without crush ?
```

Original comment by `TMS2...@gmail.com` on 21 Jan 2008 at 10:57

**Comment by GoogleCodeExporter** [comment]
```
Glad that the problem is resolved.

As you may know IE is a wrapper for Webbrowser control as is csExWB control. My 
guess is that there was a problem with loading the offending dll in IE, but 
internally it bypassed it. To acheive the same effect, I needed to know where 
the 
crash occured and why. That is why I asked you (if possible) to create a fresh 
and 
simple project to track down the routine that can be used to stop the crash. 
Now 
that the crash is resolved, there is no way for me to know how to prevent such 
problems in the future. Please keep in mind that I do rely on the feedback of 
the 
fellow developers to improve and enhance this control.

MH


```

Original comment by `mehr...@gmail.com` on 21 Jan 2008 at 12:41
- Changed state: **Fixed**
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**
