### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuza55/csexwb2#32]
```
Here's the error:
Exception: System.Runtime.InteropServices.COMException
Message: The specified procedure could not be found. (Exception from 
HRESULT: 0x8007007F)
Source: 
Stacktrace:    at System.RuntimeType.ForwardCallToInvokeMember(String 
memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, 
MessageData& msgData)
   at IfacesEnumsStructsClasses.IWebBrowser2.Navigate(String URL, Object& 
Flags, Object& TargetFrameName, Object& PostData, Object& Headers)
   at csExWB.cEXWB.Navigate(String URL)
   at csExWB.cEXWB.InternalCreateWB()
   at csExWB.cEXWB.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& 
m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)

I'm sorry but I don't have more info, since this is from remote log. It's 
from Windows XP or higher for sure. Version of the control was 1.0.0.3. 
Now I switched to 1.0.0.7, hope it helps. Any idea what might be the 
problem?
```

Original issue reported on code.google.com by `sec....@gmail.com` on 14 Apr 2008 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Error codes 0x8007007f OR 0x8007007e can be the result of a problem during the 
install of a service pack. After the service pack install you have missing 
files, 
file mismatches, and corrupted files.

To workaround this problem, uninstall the service pack that you recently 
installed 
and reinstall it.

MH

```

Original comment by `mehr...@gmail.com` on 14 Apr 2008 at 4:08

**Comment by GoogleCodeExporter** [comment]
```
I had a similar error that resulted from my attempting to use the csExWb 
control 
with an [MTAThread] instead of the COM interop appropriate [STAThread]. For me 
the 
problem emerged in a Console project since these are not [STAThread] by 
default. The 
fix was to declare the apartment threading:
    static class Program
    {
        [STAThread]                  <--add this line
        static void Main()
        {
            Application.Run(new SuperDuperCsExWbApp());
        }
    }

Similarly this kind of error can show up if initializing the csExWb control as 
a 
static object.

Hope that's helpful.
```

Original comment by `vcolb...@gmail.com` on 1 Jul 2008 at 9:19

**Comment by GoogleCodeExporter** [comment]
```
Thank you.

Regards,

MH
```

Original comment by `mehr...@gmail.com` on 2 Jul 2008 at 10:15
