### ISSUE TITLE
Crash after trying to close a popupp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuza55/csexwb2#41]
```
What steps will reproduce the problem?
1. Open popupp
2.
3.

What is the expected output? What do you see instead?
See below..
What are the OS and IE versions?
Xp SP2 IE6
What version of the product are you using?
2.X

Please provide any additional information below.
I open a popupp via java script. javascript:void window.open("",""....);

It contains login session

If i open it the first time it will work OK, but if I close the window and 
open it again it will just open a gray window and when i try to close it 
it will ouput this error

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80004005): Unspecified 
error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, 
BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& 
msgData)
   at IfacesEnumsStructsClasses.IWebBrowser2.Navigate(String URL, Object& 
Flags, Object& TargetFrameName, Object& PostData, Object& Headers)
   at csExWB.cEXWB.NavToBlank() in C:\Documents and 
Settings\Teknikpc\Desktop\testmapp\csExWBv2
[1].0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\csExWB\
cEXWB.cs:line 1512
   at DemoApp.frmPopup.frmPopup_FormClosing(Object sender, 
FormClosingEventArgs e) in C:\Documents and 
Settings\Teknikpc\Desktop\testmapp\csExWBv2
[1].0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\DemoApp
\frmPopup.cs:line 61
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& 
m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: 
file:///C:/WINNT/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
DemoApp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%
20Settings/maku06/Desktop/orginalWeb/DemoApp.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: 
file:///C:/WINNT/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c5619
34e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: 
file:///C:/WINNT/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.
dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: 
file:///C:/WINNT/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a
/System.Drawing.dll
----------------------------------------
csExWB
    Assembly Version: 2.0.0.1
    Win32 Version: 2.0.0.1
    CodeBase: file:///C:/Documents%20and%
20Settings/maku06/Desktop/orginalWeb/csExWB.DLL
----------------------------------------
Interop.ComUtilitiesLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%
20Settings/maku06/Desktop/orginalWeb/Interop.ComUtilitiesLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase: 
file:///C:/WINNT/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/
Accessibility.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: 
file:///C:/WINNT/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/Syste
m.Web.dll
----------------------------------------



```

Original issue reported on code.google.com by `tti.prog...@gmail.com` on 19 May 2008 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
I now see that the secon poppup point to the url C:\WINNT\Web\source.htm ?!
Whats upp whit that.
```

Original comment by `tti.prog...@gmail.com` on 20 May 2008 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
"If i open it the first time it will work OK, but if I close the window and 
open it again it will just open a gray window and when i try to close it 
it will ouput this error"

The error suggests that the Webbrowser contained in frmPopup was disposed after 
the 
first display. As a call to NavToBlank in frmPopup.frmPopup_FormClosing event 
is 
generating the exception. Please note that after closing the frmPopup, it calls 
NavToBlank and hides the form (if launched from frmMain via NewWindow2,...).

Does the login page make a call to window.close?
If the answer is yes, please adjust the code in the 
frmPopup.cEXWB1_WindowClosing 
event to:

            if (isSecondaryPopup)
                return;
            e.Cancel = true;
            this.cEXWB1.NavToBlank();
            this.Hide();

MH









```

Original comment by `mehr...@gmail.com` on 20 May 2008 at 7:33

**Comment by GoogleCodeExporter** [comment]
```
Yes it makes a call to window.close I made a workaround where each cEXWB open 
there 
own frmPopup and close it instead for hiding it. But ill try your suggeestion.

Thx ill replay later the result.
```

Original comment by `tti.prog...@gmail.com` on 21 May 2008 at 9:56
