### ISSUE TITLE
Unable to cast COM object of type 'ComUtilitiesLib.UtilManClass' to interface type 'ComUtilitiesLib.IUtilMan'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuza55/csexwb2#46]
```

System.InvalidCastException was unhandled
  Message="Unable to cast COM object of type 'ComUtilitiesLib.UtilManClass'
to interface type 'ComUtilitiesLib.IUtilMan'. This operation failed because
the QueryInterface call on the COM component for the interface with IID
'{DD264321-7025-476C-8B7A-850E0B79DD41}' failed due to the following error:
No such interface supported (Exception from HRESULT: 0x80004002
(E_NOINTERFACE))."
  Source="Interop.ComUtilitiesLib"
  StackTrace:
       at ComUtilitiesLib.UtilManClass.set_HWNDInternetExplorerServer(Int32
pVal)
       at csExWB.cEXWB.StartApp() in
E:\csExWBv2.0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\csEx
WB\cEXWB.cs:line
1436
       at csExWB.cEXWB.WBIEServerHandle() in
E:\csExWBv2.0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\csEx
WB\cEXWB.cs:line
1122
       at csExWB.cEXWB.get_IEServerHwnd() in
E:\csExWBv2.0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\csEx
WB\cEXWB.cs:line
551
       at csExWB.cEXWB.IEServerWindow.TimerProc(Object state) in
E:\csExWBv2.0_Includes_ComUtilities\csExWBv2.0_Includes_ComUtilities\csExWB\csEx
WB\cEXWB.cs:line
5300
       at System.Threading._TimerCallback.TimerCallback_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
       at System.Threading._TimerCallback.PerformTimerCallback(Object state)

```

Original issue reported on code.google.com by `JerryAnd...@gmail.com` on 7 Jun 2008 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Have you registered ComUtilities.dll?

MH
```

Original comment by `mehr...@gmail.com` on 9 Jun 2008 at 11:07
